### ISSUE TITLE
Broken link to font file

### ISSUE THREAD

**Issue by JeanMertz** [drone/drone#1080]
0.4 uses the following font file, which returns a `404`:

http://cdn.rawgit.com/zavoloklom/material-design-iconic-font/master/css/material-design-iconic-font.min.css

**Comment by caarlos0** [comment]
Hey @JeanMertz, it should be fixed now!

**Comment by JeanMertz** [comment]
:+1: @caarlos0

**Comment by JeanMertz** [comment]
@bradrydzewski please note that this wasn't actually fixed properly (see my PR comment).

**Comment by bradrydzewski** [comment]
the rawgit reference was completely removed and replaced with a reference to the official material design icon library:

```
@import url(//fonts.googleapis.com/icon?family=Material+Icons);
```
