### ISSUE TITLE
drone exec ignores when: local: false

### ISSUE THREAD

**Issue by josmo** [drone/drone#2021]
Drone version:
.6

Repro steps:
1. create a .drone.yml file with some steps that have secrets
2. add { when: { local: false }}  yml equiv to the steps with secrets
3. run drone exec

if will try to still run the containers that are marked for local: false

from a conversation with @bradrydzewski it looks like this may have been lost from .5 but should get brought back into .6

**Comment by josmo** [comment]
https://github.com/cncd/pipeline/pull/4 should fix this. It add the functionality that got removed when the pipeline was moved to a lib.

**Comment by bradrydzewski** [comment]
fixed

**Comment by rberner** [comment]
I don't see anything about 'local:true|false' in the documentation anymore, and I'm still seeing the same bug as described. Setting 'when:local:false' doesn't seem to affect local execution, the steps will still run. Can someone verify this is no longer a working feature?

**Comment by bradrydzewski** [comment]
If you want to control which pipeline are executed locally you can use the include and exclude flags. See https://docs.drone.io/quickstart/cli/#run-specific-steps
