### ISSUE TITLE
Bitbucket only 100 repositories synced on 1.0.0-rc1

### ISSUE THREAD

**Issue by nathan-fps** [drone/drone#2533]
If an account on bitbucket has access to more than 100 repositories, it seems that only 100 of them are synced to drone. This occurs in version 1.0.0-rc.1. Further discussion is available in [discourse]( https://discourse.drone.io/t/1-0-0-rc-1-drone-repository-filter-not-respected-for-bitbucket/3023) and on issue #1667.

**Comment by nathan-fps** [comment]
The [implementation](https://github.com/drone/go-scm) relies on optional pagination fields that are not present at the `/2.0/repositories` endpoint. As the [Bitbucket API documentation](https://developer.atlassian.com/bitbucket/api/2/reference/meta/pagination) documentation states, only the `values` and `next` field are required to be present. To fix this issue, it seems the bitbucket driver needs to implement pagination by calling the `next` url repeatedly instead of incrementing the page number.

**Comment by bradrydzewski** [comment]
the current code uses the `next` field for the next page [1][2] and we also have a unit test (based on a real payload) that checks to ensure we extract the correct data [3]. Sorry if I'm not understanding the issue correctly. Perhaps you could send a PR if you are able to identify the root cause?

[1] https://github.com/drone/go-scm/blob/a196f4de0e3f33e812205591b69c2d1ef6eaa291/scm/driver/bitbucket/repo.go#L91
[2] https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/util.go#L93 
[3] https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/repo_test.go#L117

**Comment by nathan-fps** [comment]
Ok, so after a bit more reading and experimentation I've found the root cause. The fix implemented in #1667 resulted in a slightly modified response from the API. So, if you hit the `/2.0/repositories/{owner}` endpoint you get a response that looks like this:
```
{
  "pagelen": 10,
  "size": 15,
  "values": [
    .
    .
  ],
  "page": 1,
  "next": "https://api.bitbucket.org/2.0/repositories/{owner}?page=2"
}
```
Unfortunately, when you hit the `/2.0/repositories?role=member` endpoint you get a response that
looks like this:
```
{
  "pagelen": 10,
  "values": [
     .
     .
  ],
  "next": "https://api.bitbucket.org/2.0/repositories?after={some iso-8601 url-formatted timestamp}&role=member"
}
```
The issue with [1][2] is that it doesn't actually use the URL in `next` to make the next request. It just parses the query string in `next` to find the next page and then assumes the form of the next path will be `/2.0/repositories?role=member&page=%d`. 

I'll open a PR and start some work on this if you like. I'm still trying to wrap my head around the logic of the repository so it might take me a bit of time to get something ready.

[1][https://github.com/drone/go-scm/blob/a196f4de0e3f33e812205591b69c2d1ef6eaa291/scm/driver/bitbucket/repo.go#L91](https://github.com/drone/go-scm/blob/a196f4de0e3f33e812205591b69c2d1ef6eaa291/scm/driver/bitbucket/repo.go#L91)
[2][https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/util.go#L93](https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/util.go#L93)

**Comment by bradrydzewski** [comment]
Thanks for the analysis, I see the issue you are describing now. The challenge is that the `go-scm` library tries to abstract all the providers (github, gitlab, bitbucket, etc) to a common set of structures and api calls. Ideally we can implement a fix in such a way that avoid a leaky abstraction. I have jotted some ideas / pseudo code below to help with the design / path.

One option could be to return the next URL in the Page object:

```diff
	// Page represents parsed link rel values for
	// pagination.
	Page struct {
		Next      int
+		NextURL   string
		Last      int
		First     int
		Prev      int
	}
```

When paging through results you could pass both the URL and page number. The implementation (e.g. Bitbucket, GitHub, etc) would choose to use the URL or would choose to construct the endpoint from the page and size parameters. Initially only Bitbucket would use the URL. 

```diff
	// ListOptions specifies optional pagination
	// parameters.
	ListOptions struct {
+		URL string
		Page int
		Size int
	}
```

The Bitbucket driver could be adjusted to work like this:

```diff
// List returns the user repository list.
func (s *repositoryService) List(ctx context.Context, opts scm.ListOptions) ([]*scm.Repository, *scm.Response, error) {
	path := fmt.Sprintf("2.0/repositories?%s", encodeListRoleOptions(opts))
+	if opts.URL != "" {
+		path = opts.URL
+	}
	out := new(repositories)
	res, err := s.client.do(ctx, "GET", path, nil, &out)
	copyPagination(out.pagination, res)
	return convertRepositoryList(out), res, err
}
```

We could then modify the underlying Drone code (below) to ensure both the page number and page url are passed to the API call.

```diff
	repos := []*drone.Repository{}
	opts := scm.ListOptions{Size: 100}
	for {
		result, meta, err := s.client.Repositories.List(ctx, opts)
		if err != nil {
			return nil, err
		}
		for _, src := range result {
			repos = append(repos, convertRepository(src))
		}
		opts.Page = meta.Page.Next
+		opts.URL = meta.Page.NextURL

-		if opts.Page == 0 {
+		if opts.Page == 0 || opts.URL == "" {
			break
		}
	}
```

Over time we could consider supporting the `URL` field for all providers, but in the short term, we can just focus on getting something working for Bitbucket.

**Comment by nathan-fps** [comment]
Agreed, I think you're incremental approach looks good in the short term. I'll have a PR in shortly.

**Comment by nathan-fps** [comment]
@bradrydzewski I believe you'll want the termination condition to be `opts.Path == 0 && opts.URL == ""`.

**Comment by luizfelipepg** [comment]
Any updates ?

I am also having problems and unable to see all my repos :/

**Comment by bradrydzewski** [comment]
@nathan-fps submitted a patch which is included in the `rc.3` image. Perhaps he can let us know once he has had the chance to test (thanks Nathan!)

**Comment by nathan-fps** [comment]
Sweet, I'll test that out tomorrow morning :)

**Comment by robert-bo-davis** [comment]
The problem is solved in rc.3. Thanks!

**Comment by luizfelipepg** [comment]
I might be missing something :/
For me still doesn't work :/

**Comment by bradrydzewski** [comment]
Just to clarify, this thread is related to Bitbucket Cloud.  Are you using Bitbucket Cloud, or are you using Atlassian Stash (aka Bitbucket Server) which is a completely different implementation.

**Comment by luizfelipepg** [comment]
I am using bitbucket cloud.

Here is the image I am using:
<img width="462" alt="screen shot 2018-12-18 at 9 41 11 am" src="https://user-images.githubusercontent.com/863641/50120269-1d8cb500-02a9-11e9-9d84-6ba160a8c36d.png">

And here is the API returning 100 repos:

<img width="1440" alt="screen shot 2018-12-18 at 9 43 07 am" src="https://user-images.githubusercontent.com/863641/50120533-e8349700-02a9-11e9-8e19-95d53ede14b9.png">

**Comment by bradrydzewski** [comment]
do you need to re-sync your repository list, by clicking the SYNC button on the same page?

**Comment by luizfelipepg** [comment]
I did few times and can see in the logs:

 {"level":"debug","login":"x","msg":"syncer: begin repository sync","time":"2018-12-17T22:51:17Z"}
{"level":"debug","login":"x","msg":"syncer: finished repository sync","time":"2018-12-17T22:51:20Z"} 

But repos don't change

**Comment by luizfelipepg** [comment]
My env variables:

<img width="604" alt="screen shot 2018-12-18 at 9 57 33 am" src="https://user-images.githubusercontent.com/863641/50120957-65144080-02ab-11e9-8ce2-76f4526ef0ce.png">

**Comment by bradrydzewski** [comment]
DRONE_REPOSITORY_FILTER will limit your repository list to only repositories that match `bitbucket.org/bitbucket-team`. Not sure if that is impacting in some way ....

**Comment by luizfelipepg** [comment]
Thanks for the review @bradrydzewski .

I guess the DRONE_REPOSITORY_FILTER shouldn't be a problem because the "bitbucket-team" is actually my bitbucket team id which is in every repo name I have. I will remove it and test though.

I will remove the invalid ones as well :) thanks :)

**Comment by luizfelipepg** [comment]
@bradrydzewski 

I removed all invalid parameters and got this:

<img width="716" alt="screen shot 2018-12-18 at 10 14 01 am" src="https://user-images.githubusercontent.com/863641/50121714-b4f40700-02ad-11e9-8739-a6f66be45b88.png">

**Comment by nathan-fps** [comment]
@luizfelipepg I've added DRONE_REPOSITORY_FILTER to my config and things are still working. I think your problem may be unrelated

**Comment by luizfelipepg** [comment]
ok ok, I found the problem, I guess rc3 image was overwritten ? 
I had my config to only pull images if doesn't exist, when I changed to always pull new image, it worked :)
