### ISSUE TITLE
Gitea token API change breaking Gitea-Drone authentication ("Login Failed. Forbidden")

### ISSUE THREAD

**Issue by jonny5532** [drone/drone#2704]
I have been experiencing this issue: https://github.com/go-gitea/gitea/issues/6883 which I believe is caused by a recent Gitea commit: ( https://github.com/go-gitea/gitea/commit/46373e765702a203bfcb576c9d3639314ef4965f#diff-e8b760d6f593a855db95ca635708d685L9470 ) which has changed the create-token API response.

Specifically, the key called 'sha1' (containing the token) has seemingly changed name to 'token'.

This means that the following code is no longer correct:

https://github.com/drone/go-login/blob/0e45116bc8185ecedcc4e6d6f7e70b4a12b75623/login/gogs/handler.go#L43

However, this also represents a breaking change between Gogs and Gitea authentication - thus it would be necessary to separate out a Gitea-specific routine in go-login (which currently uses the same code for Gogs and Gitea).

Should Gitea instead be asked to revert this change to restore compatibility?

**Comment by tboerger** [comment]
Gitea already reverted the breaking change at https://github.com/go-gitea/gitea/pull/6903

**Comment by jonny5532** [comment]
Ah, I didn't spot that!

Can confirm that the problem seems to have been fixed in Gitea 1.9.0+dev-231-g34eee25bd (Drone is now authenticating correctly without the error).

**Comment by techknowlogick** [comment]
Now that’s Gitea can act as an OAuth2 provider that is the more secure way of authentication, rather than entering your password into a different system. Basic Auth also doesn’t work with 2FA which should be used.

**Comment by balthild** [comment]
Hello. I've upgraded Gitea to `1.9.0+dev-231-g34eee25bd`, but drone still says `Login Failed. Forbidden` always. How could I debug where the problem is happened? The `DRONE_LOGS_DEBUG` seems useless because there's no log about authentication was output.

**Comment by jonny5532** [comment]
You can test for the buggy Gitea by doing:

curl -u <username>:<password> -X POST "https://<hostname>/api/v1/users/<username>/tokens" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"name\": \"test1\"}"

(where username/password is a Gitea login and hostname the Gitea instance) and seeing if the response includes "token":"...." instead of "sha1":"...". If it includes "sha1":"...", then this bug isn't the problem and you have something else going on.

Also look in the Gitea logs for the pattern described in https://github.com/go-gitea/gitea/issues/6883 (a successful /tokens call but a failed /user call).

**Comment by lafriks** [comment]
This should be fixed by go-gitea/gitea#6903

**Comment by jonny5532** [comment]
I don't think it is fixed - whilst the key change from "token" back to "sha1" does mean that you can log in, a more significant change in Gitea (no longer storing the original tokens) means that you can only log in once.

When you try and log in a second time, Drone first queries Gitea for a token called "drone", to avoid creating another. However, Gitea isn't storing the tokens anymore, so it returns an empty string, and the above issue recurs.

Unless Gitea want to revert their not-storing-plaintext-tokens change, then Drone will either need to force Gitea users to switch to the OAuth2 method, or change the login mechanism so that it recreates a token each time (via POST /api/..../tokens).

**Comment by techknowlogick** [comment]
@jonny5532 https://github.com/go-gitea/gitea/pull/6912 will change name of drone token, so that basic auth will still continue to work. Note it'll populate the list of tokens for the user with a token per drone login.

**Comment by jonny5532** [comment]
I can see how this works but it seems a bit of a hack - as you say it will result in a new token per login so if there is there some upper limit on the number of tokens that can exist, then that will be a problem, as well as looking bad in the token list in Gitea.

I also can't see an immediate need to deprecate the non-OAuth2 method - whilst OAuth2 is better, the old method can still be implemented correctly. Drone could store the token locally after it creates it, rather than relying on being able to get the existing token on login. Alternatively Drone could always create a new token on login, but it would seem sensible for it to also delete the old one, which will require that the "drone" token name has a unique suffix so that multiple Drones don't delete each others' keys (presumably there is a per-instance unique value that could be used?).

**Comment by jonny5532** [comment]
How about this:

https://github.com/jonny5532/go-login/blob/cac371539f981223aad0a4e028338dbb37a7ebc5/login/gogs/handler.go#L57

(modifying drone/go-login to delete empty tokens first, and then recreate, which will work, and avoid creating another token in Gitea every time you log in).

This is only half the solution - Drone will need changing to use a unique token Label per installation (not just "drone") in case people are using multiple Drone instances on a single Gitea installation.

Thoughts?

**Comment by techknowlogick** [comment]
Gitea already doesn't allow basic auth for users that have 2FA enabled on their accounts so using Basic auth already is less secure than using OAuth2, I don't think Drone should be patched at all to resolve the breaking change from Gitea, instead users should switch to OAuth2.

As we've seen from recent attacks against SCM providers, 2FA is essentially mandatory if you want to keep your code safe.

**Comment by jonny5532** [comment]
Re: deletion, I proposed naming the tokens with a unique per-installation token, although I  don't know enough about Drone to know if that is sufficient.

If the non-OAuth2 mechanism is now deprecated, can the Drone docs be updated to reflect this? I anticipate a number of new Drone+Gitea users encountering this issue as I ding d.

(Are the docs something I can contribute to with a PR?)

**Comment by bradrydzewski** [comment]
@techknowlogick agreed, we can completely deprecate basic authentication in favor of oauth. I will plan on removing basic auth from the upcoming 1.2 release.

**Comment by vtolstov** [comment]
i can't run gitea latest with drone latest:
```
May 14 00:51:08 central01.z1.unistack.org dockerd-current[1517]: [Macaron] 2019-05-13 21:51:08: Completed POST /login/oauth/access_token
 400 Bad Request in 111.668282ms
May 14 00:51:08 central01.z1.unistack.org docker[9968]: [Macaron] 2019-05-13 21:51:08: Completed POST /login/oauth/access_token 400 Bad 
Request in 111.668282ms
May 14 00:51:08 central01.z1.unistack.org dockerd-current[1517]: {
May 14 00:51:08 central01.z1.unistack.org dockerd-current[1517]:   "level": "error",
May 14 00:51:08 central01.z1.unistack.org docker[9769]: {
May 14 00:51:08 central01.z1.unistack.org docker[9769]:   "level": "error",
May 14 00:51:08 central01.z1.unistack.org docker[9769]:   "msg": "oauth: cannot exchange code: eTVP89ej7zGJKi6IIQn29gp1AgU9r5AEOFs545m96
Sc=: unauthorized_client: client is not authorized",
```

**Comment by vtolstov** [comment]
i solved this issue. but have another - webhook from gitea not sent to drone. but if i create hook by hand it run success.

**Comment by techknowlogick** [comment]
I've just submitted a PR to entirely remove basic auth as an option for Gitea in Drone, this ensures users must use OAuth2 for logging into Drone. PR is https://github.com/drone/drone/pull/2721

**Comment by sloonz** [comment]
Gitea OAuth2 is not documented yet : there is no mention of DRONE_GITEA_CLIENT_ID and DRONE_GITEA_CLIENT_SECRET on https://docs.drone.io/installation/gitea/ and https://docs.drone.io/reference/

**Comment by tboerger** [comment]
Updating the docs can only be done by Brad as the current docs are not published to a public git repo.

**Comment by clintwood** [comment]
@vtolstov Can you explain how you ['i solved this issue'](https://github.com/drone/drone/issues/2704#issuecomment-492000739).  I'm getting the dreaded `oauth: cannot exchange code:...` error.  I'm running Gitea & Drone latest inside docker on the same host. Thanks!

**Comment by tboerger** [comment]
HTTPS is not required by oauth2

**Comment by clintwood** [comment]
@vtolstov, @tboerger, thank you I have resolved it (after a few days)!  I had to open up my firewall to allow the docker container (drone in this case) to access the 'external network' (in my case a VPN address 192.168.0.0/24) -  FWIW I had to setup the container to use a known ip range to allow correct firewall setup in my docker-compse.yml fie:

```
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
```

**Comment by wxk6b1203** [comment]
I followed @kimpenhaus ' guide to configured my [gitea](gitea.io) and it really works. 
> Running both gitea and drone on latest docker images (managed by [containrrr/watchtower](https://github.com/containrrr/watchtower) - which is the newly maintained v2tec/watchtower).
> 
> 1. You need to register drone application in gitea. `settings -> applications -> Manage OAuth2 applications`
> 
> <img alt="Bildschirmfoto 2019-05-14 um 09 16 04" width="1143" src="https://user-images.githubusercontent.com/575109/57678530-b1309a80-7629-11e9-8bfc-7be5632a9188.png">
> 
> 1. The `Redirect URI` must be identical to that used from drone. Mine is https://:/login
> 
> ![Bildschirmfoto 2019-05-14 um 09 16 15](https://user-images.githubusercontent.com/575109/57678591-d91ffe00-7629-11e9-983b-8b29ddfce1bb.png)
> 
> 1. You need to set the env parameters in the docker container `DRONE_GITEA_CLIENT_ID` and `DRONE_GITEA_CLIENT_SECRET` - both generated in step 1./2. after saving.
> 2. What I need to adjust was `DRONE_SERVER_HOST` which seems to have the port also - otherwise the redirect uri is not constructed proper.
> 
> ![Bildschirmfoto 2019-05-14 um 09 17 04](https://user-images.githubusercontent.com/575109/57678741-2603d480-762a-11e9-84ab-ba274fe03319.png)
> 
> That's it...

In my opinion, and is just a suggesstion, OAuth2 Application should be detached with Drone's environment. Other wise, a normal user instead of admin should create his own OAuth Application to bind with Drone CI. Until now, all users on one gitea environment use the same OAuth2 app. This leads to flexiblity of  creating code platform - DroneCI binding.

**Comment by tboerger** [comment]
A normal user can't attach any oauth app as it got to be configured on start of drone via env variables by an admin

**Comment by netlander** [comment]
This problem is still not solved.
Anyone cares to share a combination of Gitea version that works with a Drone version?!

**Comment by techknowlogick** [comment]
@netlander please ensure you are running latest version of drone and Gitea. Gitea is at 1.12.5 and Drone is 1.9.1

**Comment by netlander** [comment]
@techknowlogick Just tried these exact two versions, both running on docker, and got the exact same result:
```
{"level":"error","msg":"oauth: cannot exchange code: 3uSb2Q82nbpspJjTvW1l_mSuzGbqFUmkaopoiLMleAs=: : ","time":"2020-10-10T19:16:20Z"}
```

**Comment by shotor** [comment]
I'm experiencing the same issue with latest of gitea and drone

I'm running both apps on a separate docker bridge network. Gitea is behind an nginx proxy served over https. The dns record for that url is public. Drone runs on http on port 80, and I have a dns record for that as well.

I get the gitea authorize scree, when I click OK it calls drone and times out

**Comment by netlander** [comment]
Personally moved on to a more mature and stable CI CD solution that goes by the name Jenkins.😅

**Comment by shotor** [comment]
> Personally moved on to a more mature and stable CI CD solution that goes by the name Jenkins.

No please, not that again! :smile: 

https://concourse-ci.org/ looks pretty good
